/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samuelflores_examen2;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Samuel
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        user.cargarArchivo();
        System.out.println(user.getListaUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registrar = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lb_foto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        tf_nombre = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        tf_usuario1 = new javax.swing.JTextField();
        tf_contrasena = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jd_usuarionormal = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jd_publicaciones = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_autor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_privacidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_publicacion = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jd_usuarioadministrador = new javax.swing.JDialog();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jd_listarpublicaciones = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        popup_menu = new javax.swing.JPopupMenu();
        jmi_agregarcomentario = new javax.swing.JMenuItem();
        jmi_agregarresultado = new javax.swing.JMenuItem();
        jd_agregarcomentario = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_comentario = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jd_tree_solicitudes = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        menu_popup = new javax.swing.JPopupMenu();
        jmi_agregaramigo = new javax.swing.JMenuItem();
        jmi_rechazaramigo = new javax.swing.JMenuItem();
        jd_tree_amigos = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_tree_amigos = new javax.swing.JTree();
        jd_tree_publicaciones = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_tree_publicaciones = new javax.swing.JTree();
        menu_pop = new javax.swing.JPopupMenu();
        jmi_eliminarpubli = new javax.swing.JMenuItem();
        jd_jlist_publicaciones = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jd_agregar_resultado = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ta_respuesta = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jd_lista_Publicaciones = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jl_list = new javax.swing.JList<>();
        pop_menu = new javax.swing.JPopupMenu();
        jmi_bloquear = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jd_lis_publica = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pf_contrasena = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Registrar");

        jLabel6.setText("Nombre completo");

        jLabel7.setText("Correo");

        jLabel8.setText("Fecha");

        jLabel9.setText("Usuario");

        jLabel10.setText("Contrasena");

        jLabel11.setText("Imagen");

        jButton2.setText("Registrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel13.setText("Escoja el tipo de Usuario");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UsuarioAdministrador", "UsuarioNormal", " " }));

        jButton3.setText("Seleccionar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registrarLayout = new javax.swing.GroupLayout(jd_registrar.getContentPane());
        jd_registrar.getContentPane().setLayout(jd_registrarLayout);
        jd_registrarLayout.setHorizontalGroup(
            jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registrarLayout.createSequentialGroup()
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_registrarLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel11)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registrarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton3)
                                .addGap(20, 20, 20)))
                        .addComponent(lb_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96)
                        .addComponent(jButton2))
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(56, 56, 56)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_nombre)
                                .addComponent(tf_correo)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_contrasena))
                            .addComponent(tf_usuario1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)))
                .addContainerGap())
            .addGroup(jd_registrarLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_registrarLayout.setVerticalGroup(
            jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registrarLayout.createSequentialGroup()
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_registrarLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(56, 56, 56)
                                .addComponent(jButton3))))
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        jMenu1.setText("Usuario Normal");

        jMenu2.setText("Publicaciones");

        jMenuItem1.setText("Realizar Publicaciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Listar Publicaciones");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu1.add(jMenu2);

        jMenu3.setText("Amistades");

        jMenuItem3.setText("Enviar Solicitudes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Jtree solicitudes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Jtree amistades");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenu1.add(jMenu3);

        jMenu4.setText("Informacion Personal");

        jMenuItem6.setText("Modificar informacion");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Eliminar cuenta");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenu1.add(jMenu4);

        jMenuItem8.setText("JTree Publicaciones");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Jlist Publicaciones problemas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem13.setText("About");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem11.setText("Salir");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jd_usuarionormal.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_usuarionormalLayout = new javax.swing.GroupLayout(jd_usuarionormal.getContentPane());
        jd_usuarionormal.getContentPane().setLayout(jd_usuarionormalLayout);
        jd_usuarionormalLayout.setHorizontalGroup(
            jd_usuarionormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_usuarionormalLayout.setVerticalGroup(
            jd_usuarionormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jLabel12.setText("ID:");

        jLabel14.setText("Autor: ");

        jLabel15.setText("Privacidad: ");

        jLabel16.setText("Mensaje");

        ta_publicacion.setColumns(20);
        ta_publicacion.setRows(5);
        jScrollPane1.setViewportView(ta_publicacion);

        jButton4.setText("Realizar publicaciones");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Realizar Publicaciones");

        javax.swing.GroupLayout jd_publicacionesLayout = new javax.swing.GroupLayout(jd_publicaciones.getContentPane());
        jd_publicaciones.getContentPane().setLayout(jd_publicacionesLayout);
        jd_publicacionesLayout.setHorizontalGroup(
            jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_publicacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_publicacionesLayout.createSequentialGroup()
                        .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_publicacionesLayout.createSequentialGroup()
                                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jd_publicacionesLayout.createSequentialGroup()
                                        .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14))
                                        .addGap(23, 23, 23)
                                        .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_id)
                                            .addComponent(tf_autor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                                    .addGroup(jd_publicacionesLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_privacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addGroup(jd_publicacionesLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_publicacionesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jd_publicacionesLayout.setVerticalGroup(
            jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_publicacionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(36, 36, 36)
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(tf_privacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jMenu5.setText("Usuario Administrador");

        jMenuItem10.setText("Jlist Publicaciones ");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem14.setText("About");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem12.setText("Salir");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar2.add(jMenu5);

        jd_usuarioadministrador.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jd_usuarioadministradorLayout = new javax.swing.GroupLayout(jd_usuarioadministrador.getContentPane());
        jd_usuarioadministrador.getContentPane().setLayout(jd_usuarioadministradorLayout);
        jd_usuarioadministradorLayout.setHorizontalGroup(
            jd_usuarioadministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_usuarioadministradorLayout.setVerticalGroup(
            jd_usuarioadministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Listar Publicaciones");

        lista.setModel(new DefaultListModel());
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lista);

        javax.swing.GroupLayout jd_listarpublicacionesLayout = new javax.swing.GroupLayout(jd_listarpublicaciones.getContentPane());
        jd_listarpublicaciones.getContentPane().setLayout(jd_listarpublicacionesLayout);
        jd_listarpublicacionesLayout.setHorizontalGroup(
            jd_listarpublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarpublicacionesLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listarpublicacionesLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jd_listarpublicacionesLayout.setVerticalGroup(
            jd_listarpublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarpublicacionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jmi_agregarcomentario.setText("Agregar Comentario");
        jmi_agregarcomentario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_agregarcomentarioMouseClicked(evt);
            }
        });
        jmi_agregarcomentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarcomentarioActionPerformed(evt);
            }
        });
        popup_menu.add(jmi_agregarcomentario);

        jmi_agregarresultado.setText("Agregar Resultado");
        jmi_agregarresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarresultadoActionPerformed(evt);
            }
        });
        popup_menu.add(jmi_agregarresultado);

        ta_comentario.setColumns(20);
        ta_comentario.setRows(5);
        jScrollPane3.setViewportView(ta_comentario);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Comentario");

        jButton5.setText("Agregar Comentario");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarcomentarioLayout = new javax.swing.GroupLayout(jd_agregarcomentario.getContentPane());
        jd_agregarcomentario.getContentPane().setLayout(jd_agregarcomentarioLayout);
        jd_agregarcomentarioLayout.setHorizontalGroup(
            jd_agregarcomentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarcomentarioLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarcomentarioLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jd_agregarcomentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarcomentarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarcomentarioLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addContainerGap())))
        );
        jd_agregarcomentarioLayout.setVerticalGroup(
            jd_agregarcomentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarcomentarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Arbol de solicitudes");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Solicitudes");
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_arbolMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jt_arbol);

        javax.swing.GroupLayout jd_tree_solicitudesLayout = new javax.swing.GroupLayout(jd_tree_solicitudes.getContentPane());
        jd_tree_solicitudes.getContentPane().setLayout(jd_tree_solicitudesLayout);
        jd_tree_solicitudesLayout.setHorizontalGroup(
            jd_tree_solicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tree_solicitudesLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jd_tree_solicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_tree_solicitudesLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_tree_solicitudesLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jd_tree_solicitudesLayout.setVerticalGroup(
            jd_tree_solicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tree_solicitudesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        menu_popup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_popupMouseClicked(evt);
            }
        });

        jmi_agregaramigo.setText("Agregar amigo");
        jmi_agregaramigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregaramigoActionPerformed(evt);
            }
        });
        menu_popup.add(jmi_agregaramigo);

        jmi_rechazaramigo.setText("Rechazar amigo");
        jmi_rechazaramigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_rechazaramigoActionPerformed(evt);
            }
        });
        menu_popup.add(jmi_rechazaramigo);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Amigos");

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Amigos");
        jt_tree_amigos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jt_tree_amigos);

        javax.swing.GroupLayout jd_tree_amigosLayout = new javax.swing.GroupLayout(jd_tree_amigos.getContentPane());
        jd_tree_amigos.getContentPane().setLayout(jd_tree_amigosLayout);
        jd_tree_amigosLayout.setHorizontalGroup(
            jd_tree_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tree_amigosLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_tree_amigosLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jd_tree_amigosLayout.setVerticalGroup(
            jd_tree_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tree_amigosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Publicaciones");

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Publicaciones");
        jt_tree_publicaciones.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_tree_publicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_tree_publicacionesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jt_tree_publicaciones);

        javax.swing.GroupLayout jd_tree_publicacionesLayout = new javax.swing.GroupLayout(jd_tree_publicaciones.getContentPane());
        jd_tree_publicaciones.getContentPane().setLayout(jd_tree_publicacionesLayout);
        jd_tree_publicacionesLayout.setHorizontalGroup(
            jd_tree_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_tree_publicacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(114, 114, 114))
            .addGroup(jd_tree_publicacionesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jd_tree_publicacionesLayout.setVerticalGroup(
            jd_tree_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tree_publicacionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jmi_eliminarpubli.setText("Eliminar Publicaciones");
        jmi_eliminarpubli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarpubliActionPerformed(evt);
            }
        });
        menu_pop.add(jmi_eliminarpubli);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("Publicaciones JList");

        jList1.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jList1);

        javax.swing.GroupLayout jd_jlist_publicacionesLayout = new javax.swing.GroupLayout(jd_jlist_publicaciones.getContentPane());
        jd_jlist_publicaciones.getContentPane().setLayout(jd_jlist_publicacionesLayout);
        jd_jlist_publicacionesLayout.setHorizontalGroup(
            jd_jlist_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jlist_publicacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(79, 79, 79))
            .addGroup(jd_jlist_publicacionesLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jd_jlist_publicacionesLayout.setVerticalGroup(
            jd_jlist_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jlist_publicacionesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Agregar Respuesta");

        ta_respuesta.setColumns(20);
        ta_respuesta.setRows(5);
        jScrollPane8.setViewportView(ta_respuesta);

        jButton6.setText("Agregar Respuesta");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregar_resultadoLayout = new javax.swing.GroupLayout(jd_agregar_resultado.getContentPane());
        jd_agregar_resultado.getContentPane().setLayout(jd_agregar_resultadoLayout);
        jd_agregar_resultadoLayout.setHorizontalGroup(
            jd_agregar_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_resultadoLayout.createSequentialGroup()
                .addGroup(jd_agregar_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregar_resultadoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(jd_agregar_resultadoLayout.createSequentialGroup()
                        .addGroup(jd_agregar_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregar_resultadoLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregar_resultadoLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel24)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_agregar_resultadoLayout.setVerticalGroup(
            jd_agregar_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_resultadoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel24)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setText("Bloquear lista de Publicaciones");

        jl_list.setModel(new DefaultListModel());
        jl_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_listMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jl_list);

        javax.swing.GroupLayout jd_lista_PublicacionesLayout = new javax.swing.GroupLayout(jd_lista_Publicaciones.getContentPane());
        jd_lista_Publicaciones.getContentPane().setLayout(jd_lista_PublicacionesLayout);
        jd_lista_PublicacionesLayout.setHorizontalGroup(
            jd_lista_PublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_lista_PublicacionesLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jd_lista_PublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane9))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jd_lista_PublicacionesLayout.setVerticalGroup(
            jd_lista_PublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_lista_PublicacionesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel25)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jmi_bloquear.setText("Bloquear Publicaciones");
        jmi_bloquear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_bloquearMouseClicked(evt);
            }
        });
        pop_menu.add(jmi_bloquear);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Publicaciones");

        jList2.setModel(new DefaultListModel());
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jList2);

        javax.swing.GroupLayout jd_lis_publicaLayout = new javax.swing.GroupLayout(jd_lis_publica.getContentPane());
        jd_lis_publica.getContentPane().setLayout(jd_lis_publicaLayout);
        jd_lis_publicaLayout.setHorizontalGroup(
            jd_lis_publicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_lis_publicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(127, 127, 127))
            .addGroup(jd_lis_publicaLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jd_lis_publicaLayout.setVerticalGroup(
            jd_lis_publicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_lis_publicaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel26)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jMenuItem15.setText("Respuestas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem15);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usuario: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Bienvenido");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Contrasena: ");

        jButton1.setText("Iniciar Sesion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setText("Registrar");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_usuario)
                    .addComponent(pf_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        jd_registrar.pack();
        jd_registrar.setLocationRelativeTo(this);
        jd_registrar.setVisible(true);
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
         JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes","png","jpg","jpeg","gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if(op==JFileChooser.APPROVE_OPTION){
            archivo=fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(100, 100, 0);
            this.lb_foto.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if(cb_tipo.getSelectedItem().equals("UsuarioAdministrador")){
            user.getListaUsuario().add(new UsuarioAdministrador(tf_nombre.getText(),tf_correo.getText(),
            null,tf_usuario1.getText(),tf_contrasena.getText(),lb_foto.getIcon()));
        }else if(cb_tipo.getSelectedItem().equals("UsuarioNormal")){
            user.getListaUsuario().add(new Usuarionormal(tf_nombre.getText(),tf_correo.getText(),
            null,tf_usuario1.getText(),tf_contrasena.getText(),lb_foto.getIcon()));
        }
        user.escribirArchivo();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        user.cargarArchivo();
         if (this.usuarioex(this.tf_usuario.getText()) && this.contra(this.pf_contrasena.getText(), tf_usuario.getText())) {
             if (log instanceof Usuarionormal) {
                 jd_usuarionormal.pack();
                 jd_usuarionormal.setLocationRelativeTo(this);
                 jd_usuarionormal.setVisible(true);
             } else if (log instanceof UsuarioAdministrador) {
                 jd_usuarioadministrador.pack();
                 jd_usuarioadministrador.setLocationRelativeTo(this);
                 jd_usuarioadministrador.setVisible(true);
             }
         }
       
             
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        publi.getListaPublicaciones().add(new Publicaciones(Integer.parseInt(tf_id.getText()),
        ta_publicacion.getText(),tf_autor.getText(),tf_privacidad.getText(),null));
        publi.escribirArchivo();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jd_publicaciones.pack();
        jd_publicaciones.setLocationRelativeTo(jd_usuarionormal);
        jd_publicaciones.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jd_listarpublicaciones.pack();
        jd_listarpublicaciones.setLocationRelativeTo(jd_usuarionormal);
        jd_listarpublicaciones.setVisible(true);
        publi.cargarArchivo();
        DefaultListModel modelo = (DefaultListModel)lista.getModel();
        for (Publicaciones t : publi.getListaPublicaciones()) {
            modelo.addElement(t);
        }
        
        lista.setModel(modelo);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            popup_menu.show(evt.getComponent(), evt.getX(), evt.getY());
            
        }
    }//GEN-LAST:event_listaMouseClicked

    private void jmi_agregarcomentarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_agregarcomentarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_agregarcomentarioMouseClicked

    private void jmi_agregarcomentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarcomentarioActionPerformed
        // TODO add your handling code here:
        jd_agregarcomentario.pack();
        jd_agregarcomentario.setLocationRelativeTo(jd_listarpublicaciones);
        jd_agregarcomentario.setVisible(true);
    }//GEN-LAST:event_jmi_agregarcomentarioActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        for (Publicaciones t : publi.getListaPublicaciones()) {
            if(t instanceof Respuesta){
                ((Respuesta)publi.getListaPublicaciones().get(lista.getSelectedIndex())).getComentarios().add(new Comentario(ta_comentario.getText()));
            }
            
        }
        
        publi.escribirArchivo();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        String salida = "";
        for (Usuario temp : user.getListaUsuario()) {
            if (temp instanceof Usuarionormal) {
                salida += user.getListaUsuario().indexOf(temp) + " ";
                salida += temp + "\n";
            }
        }
        JOptionPane.showMessageDialog(null, salida);
        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la posicion: "));
        ((Usuarionormal)log).setSolicitudes((Usuarionormal)user.getListaUsuario().get(num));
        user.escribirArchivo();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jd_tree_solicitudes.pack();
        jd_tree_solicitudes.setLocationRelativeTo(jd_usuarionormal);
        jd_tree_solicitudes.setVisible(true);
        DefaultTreeModel m = (DefaultTreeModel)jt_arbol.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)m.getRoot();
        for (Usuarionormal t : ((Usuarionormal)log).getSolicitudes()) {
            raiz.add(new DefaultMutableTreeNode(t));
        }
        m.reload();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menu_popupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_popupMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menu_popupMouseClicked

    private void jmi_agregaramigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregaramigoActionPerformed
        // TODO add your handling code here:
        String salida = "";
        for (Usuarionormal t : ((Usuarionormal) log).getSolicitudes()) {
            salida += ((Usuarionormal) log).getSolicitudes().indexOf(t) + " ";
            salida += t + "\n";
        }
        JOptionPane.showMessageDialog(null, salida);
        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la posicion: "));
        ((Usuarionormal) log).getAmigos().add(((Usuarionormal) log).getSolicitudes().get(num));
        user.escribirArchivo();
    }//GEN-LAST:event_jmi_agregaramigoActionPerformed

    private void jt_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_arbolMouseClicked
        // TODO add your handling code here:
         if (evt.isMetaDown()) {
            menu_popup.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jt_arbolMouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jd_tree_amigos.pack();
        jd_tree_amigos.setLocationRelativeTo(jd_usuarionormal);
        jd_tree_amigos.setVisible(true);
        DefaultTreeModel m = (DefaultTreeModel)jt_tree_amigos.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)m.getRoot();
        for (Usuarionormal t : ((Usuarionormal)log).getAmigos()) {
            raiz.add(new DefaultMutableTreeNode(t));
        }
        m.reload();
        user.escribirArchivo();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmi_rechazaramigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_rechazaramigoActionPerformed
        // TODO add your handling code here:
        String salida = "";
        for (Usuarionormal t : ((Usuarionormal) log).getSolicitudes()) {
            salida += ((Usuarionormal) log).getSolicitudes().indexOf(t) + " ";
            salida += t + "\n";
        }
        JOptionPane.showMessageDialog(null, salida);
        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la posicion: "));
        ((Usuarionormal)log).getSolicitudes().remove(num);
        user.escribirArchivo();
        DefaultMutableTreeNode raiz1 = new DefaultMutableTreeNode();
        DefaultTreeModel m1=new DefaultTreeModel(raiz1);
        jt_arbol.setModel(m1);
        DefaultTreeModel m = (DefaultTreeModel)jt_arbol.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)m.getRoot();
        for (Usuarionormal t : ((Usuarionormal)log).getSolicitudes()) {
            raiz.add(new DefaultMutableTreeNode(t));
        }
        m.reload();
        
    }//GEN-LAST:event_jmi_rechazaramigoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        String op = JOptionPane.showInputDialog("a)Nombre\n"
                + "b)Correo\n"
                + "c)Usuario\n"
                + "d)Contrasena\n");
        switch(op){
            case "a":
                String nombre = JOptionPane.showInputDialog("Ingrese el nuevo nombre: ");
                for (Usuario t : user.getListaUsuario()) {
                    if (t instanceof Usuarionormal) {
                        if (t.getNombre().equals(log.getNombre())) {
                            t.setNombre(nombre);
                        }
                    }

                }
                user.escribirArchivo();
                break;
            case "b":
                String correo = JOptionPane.showInputDialog("Ingrese el correo: ");
                for (Usuario t : user.getListaUsuario()) {
                    if (t instanceof Usuarionormal) {
                        if (t.getCorreo().equals(log.getCorreo())) {
                            t.setCorreo(correo);
                        }
                    }

                }
                user.escribirArchivo();
                break;
            case "c":
                String usuario = JOptionPane.showInputDialog("Ingrese el usuario: ");
                for (Usuario t : user.getListaUsuario()) {
                    if (t instanceof Usuarionormal) {
                        if (t.getUsuario().equals(log.getUsuario())) {
                            t.setUsuario(usuario);
                        }
                    }

                }
                user.escribirArchivo();
                
                break;
            case "d":
                String contrasena = JOptionPane.showInputDialog("Ingrese la contrasena: ");
                for (Usuario t : user.getListaUsuario()) {
                    if (t instanceof Usuarionormal) {
                        if (t.getContrasena().equals(log.getContrasena())) {
                            t.setContrasena(contrasena);
                        }
                    }

                }
                user.escribirArchivo();
                break;
        }
        user.escribirArchivo();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        String salida = "";
        for (Usuario temp : user.getListaUsuario()) {
            if (temp instanceof Usuarionormal) {
                salida += user.getListaUsuario().indexOf(temp) + " ";
                salida += temp + "\n";
            }
        }
        JOptionPane.showMessageDialog(null, salida);
        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la posicion: "));
        user.getListaUsuario().remove(num);
        user.escribirArchivo();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        publi.cargarArchivo();
        jd_tree_publicaciones.pack();
        jd_tree_publicaciones.setLocationRelativeTo(jd_usuarionormal);
        jd_tree_publicaciones.setVisible(true);
        DefaultTreeModel m = (DefaultTreeModel)jt_tree_publicaciones.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)m.getRoot();
        for (Publicaciones t : publi.getListaPublicaciones()) {
            raiz.add(new DefaultMutableTreeNode(t));
        }
        m.reload();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jt_tree_publicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_tree_publicacionesMouseClicked
        // TODO add your handling code here:
         if (evt.isMetaDown()) {
            menu_pop.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jt_tree_publicacionesMouseClicked

    private void jmi_eliminarpubliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarpubliActionPerformed
        // TODO add your handling code here:
        String salida = "";
        for (Publicaciones t : publi.getListaPublicaciones()) {
            if (t instanceof Publicaciones) {
                salida += publi.getListaPublicaciones().indexOf(t) + " ";
                salida += t + "\n";
            }
        }
        JOptionPane.showMessageDialog(null, salida);
        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la posicion: "));
        publi.getListaPublicaciones().remove(num);
        DefaultMutableTreeNode raiz1 = new DefaultMutableTreeNode();
        DefaultTreeModel m1=new DefaultTreeModel(raiz1);
        jt_tree_publicaciones.setModel(m1);
        DefaultTreeModel m = (DefaultTreeModel)jt_tree_publicaciones.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)m.getRoot();
        for (Publicaciones t : publi.getListaPublicaciones()) {
            raiz.add(new DefaultMutableTreeNode(t));
        }
        m.reload();
    }//GEN-LAST:event_jmi_eliminarpubliActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        for (Publicaciones t : publi.getListaPublicaciones()) {
            if(t instanceof Problemas){
                ((Problemas)publi.getListaPublicaciones().get(jl_list.getSelectedIndex()+1)).getResultado().add(new Respuesta(ta_respuesta.getText()));
            }
            
        }
        
        publi.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Realizado");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jmi_agregarresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarresultadoActionPerformed
        // TODO add your handling code here:
        jd_agregar_resultado.pack();
        jd_agregar_resultado.setLocationRelativeTo(jd_usuarionormal);
        jd_agregar_resultado.setVisible(true);
    }//GEN-LAST:event_jmi_agregarresultadoActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        publi.cargarArchivo();
        jd_lista_Publicaciones.pack();
        jd_lista_Publicaciones.setLocationRelativeTo(jd_usuarioadministrador);
        jd_lista_Publicaciones.setVisible(true);
        DefaultListModel modelo = (DefaultListModel)jl_list.getModel();
        for (Publicaciones t : publi.getListaPublicaciones()) {
            modelo.addElement(t);
        }
        jl_list.setModel(modelo);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jl_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_listMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            pop_menu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_listMouseClicked

    private void jmi_bloquearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_bloquearMouseClicked
        // TODO add your handling code here:
        ((UsuarioAdministrador)log).getPubloqueadas().add(publi.getListaPublicaciones().get(jl_list.getSelectedIndex()));
        DefaultListModel modelo1 = new DefaultListModel();
        jl_list.setModel(modelo1);
        DefaultListModel modelo = (DefaultListModel)jl_list.getModel();
        for (Publicaciones t : publi.getListaPublicaciones()) {
            modelo.addElement(t);
        }
        jl_list.setModel(modelo);
    }//GEN-LAST:event_jmi_bloquearMouseClicked

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        jd_lis_publica.pack();
        jd_lis_publica.setLocationRelativeTo(jd_usuarionormal);
        jd_lis_publica.setVisible(true);
        publi.cargarArchivo();
        DefaultListModel modelo = (DefaultListModel)jList2.getModel();
        for (Publicaciones t : publi.getListaPublicaciones()) {
            modelo.addElement(t);
        }
        jList2.setModel(modelo);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(jd_usuarionormal, "Es un programa para publicar problemas y que otros usuarios resuelvan esos problemas");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(jd_usuarioadministrador, "Es un programa para publicar problemas y que otros usuarios resuelvan esos problemas");
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        jd_agregar_resultado.pack();
        jd_agregar_resultado.setLocationRelativeTo(jd_lis_publica);
        jd_agregar_resultado.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JDialog jd_agregar_resultado;
    private javax.swing.JDialog jd_agregarcomentario;
    private javax.swing.JDialog jd_jlist_publicaciones;
    private javax.swing.JDialog jd_lis_publica;
    private javax.swing.JDialog jd_lista_Publicaciones;
    private javax.swing.JDialog jd_listarpublicaciones;
    private javax.swing.JDialog jd_publicaciones;
    private javax.swing.JDialog jd_registrar;
    private javax.swing.JDialog jd_tree_amigos;
    private javax.swing.JDialog jd_tree_publicaciones;
    private javax.swing.JDialog jd_tree_solicitudes;
    private javax.swing.JDialog jd_usuarioadministrador;
    private javax.swing.JDialog jd_usuarionormal;
    private javax.swing.JList<String> jl_list;
    private javax.swing.JMenuItem jmi_agregaramigo;
    private javax.swing.JMenuItem jmi_agregarcomentario;
    private javax.swing.JMenuItem jmi_agregarresultado;
    private javax.swing.JMenuItem jmi_bloquear;
    private javax.swing.JMenuItem jmi_eliminarpubli;
    private javax.swing.JMenuItem jmi_rechazaramigo;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JTree jt_tree_amigos;
    private javax.swing.JTree jt_tree_publicaciones;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JList<String> lista;
    private javax.swing.JPopupMenu menu_pop;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JPasswordField pf_contrasena;
    private javax.swing.JPopupMenu pop_menu;
    private javax.swing.JPopupMenu popup_menu;
    private javax.swing.JTextArea ta_comentario;
    private javax.swing.JTextArea ta_publicacion;
    private javax.swing.JTextArea ta_respuesta;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_contrasena;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_privacidad;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuario1;
    // End of variables declaration//GEN-END:variables
administrarUsuario user = new administrarUsuario("./Usuario.cmb");
Usuario log;
administrarPublicaciones publi = new administrarPublicaciones("./Publicaciones.cmb");


    public boolean usuarioex(String log) {
        for (Usuario user : user.getListaUsuario()) {
            if (user.getUsuario().equals(log)) {
                return true;
            }
        }
        return false;
    }

    public boolean contra(String pas, String useri) {
        for (Usuario usuario : user.getListaUsuario()) {
            if (usuario.getContrasena().equals(pas) && usuario.getUsuario().equals(useri)) {
                log = usuario;
                return true;
            }
        }
        return false;
    }

}
